### ISSUE TITLE
Bug with two parameters in route

### ISSUE THREAD

**Issue by svivian** [TimeToogo/RapidRoute#1]
Hey there, just giving this a whirl but there seems to be a bug when trying to use two `{...}` parameters in a route. I tried this code:

```
$router = new \RapidRoute\Router($compiledRouterPath, function (\RapidRoute\RouteCollection $routes) {
    $routes->get('/', 'News@index');
    $routes->get('/news/page/{slug}', 'News@article');
    $routes->get('/news/feed', 'News@article');
    $routes->get('/news/{num}/{slug}', 'News@article'); // bug here
});

$router->setDevelopmentMode(true);
$result = $router->match('GET', '/news/123/hello');
```

When I run it I get an error:

> Notice: Undefined offset: 1 in /.../vendor/timetoogo/rapid-route/src/Compilation/TreeBasedRouterCompiler.php on line 221
> Parse error: syntax error, unexpected ']' in /.../cache/RapidRouter.php on line 49

RapidRouter.php is my cache file. The code around line 49 is this, you can see the 'slug' array key does not have a value.

```
if ($s1 !== '') {
    switch ($method) {
        case 'GET':
        case 'HEAD':
            return [2, 'News@article', ['num' => $s1, 'slug' => ]]; // line 49
        default:
            $allowedHttpMethods[] = 'GET';
            $allowedHttpMethods[] = 'HEAD';
            break;
    }
}
```

Hope this helps :)

**Comment by TimeToogo** [comment]
Thanks for pointing this out in such detail.
This issue should now be resolved.
